"""add_xhs_note_task_models

Revision ID: 01abeaf58ff5
Revises: 6c7a5a7ece40
Create Date: 2026-05-19 16:36:26.431317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01abeaf58ff5'
down_revision: Union[str, None] = '6c7a5a7ece40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_platform'), 'tasks', ['platform'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('note_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_note_id'), 'notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_notes_platform'), 'notes', ['platform'], unique=False)
    op.create_index(op.f('ix_notes_platform_account_id'), 'notes', ['platform_account_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('note_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_assets_note_id'), 'note_assets', ['note_id'], unique=False)
    op.create_table('note_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=128), nullable=True),
    sa.Column('created_at_remote', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_comments_comment_id'), 'note_comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_note_comments_note_id'), 'note_comments', ['note_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.drop_table('post_tags')
    op.add_column('publish_assets', sa.Column('file_path', sa.Text(), nullable=True))
    op.add_column('publish_assets', sa.Column('upload_status', sa.String(length=32), nullable=True))
    op.add_column('publish_assets', sa.Column('creator_media_id', sa.String(length=128), nullable=True))
    op.add_column('publish_assets', sa.Column('upload_error', sa.Text(), nullable=True))
    op.add_column('publish_assets', sa.Column('creator_upload_info', sa.Text(), nullable=True))
    op.execute("UPDATE publish_assets SET file_path='', upload_status='pending', creator_media_id='', upload_error='', creator_upload_info='{}' WHERE file_path IS NULL")
    op.alter_column('publish_assets', 'file_path', nullable=False)
    op.alter_column('publish_assets', 'upload_status', nullable=False)
    op.alter_column('publish_assets', 'creator_media_id', nullable=False)
    op.alter_column('publish_assets', 'upload_error', nullable=False)
    op.alter_column('publish_assets', 'creator_upload_info', nullable=False)
    op.drop_column('publish_assets', 'local_path')
    op.drop_column('publish_assets', 'url')
    op.drop_column('publish_assets', 'sort_order')
    op.add_column('publish_jobs', sa.Column('source_draft_id', sa.Integer(), nullable=True))
    op.add_column('publish_jobs', sa.Column('platform', sa.String(length=32), nullable=True))
    op.add_column('publish_jobs', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('publish_jobs', sa.Column('publish_mode', sa.String(length=32), nullable=True))
    op.add_column('publish_jobs', sa.Column('publish_options', sa.Text(), nullable=True))
    op.add_column('publish_jobs', sa.Column('external_note_id', sa.String(length=128), nullable=True))
    op.add_column('publish_jobs', sa.Column('publish_error', sa.Text(), nullable=True))
    op.execute("UPDATE publish_jobs SET platform='xhs', body='', publish_mode='immediate', publish_options='{}', external_note_id='', publish_error='' WHERE platform IS NULL")
    op.alter_column('publish_jobs', 'platform', nullable=False)
    op.alter_column('publish_jobs', 'body', nullable=False)
    op.alter_column('publish_jobs', 'publish_mode', nullable=False)
    op.alter_column('publish_jobs', 'publish_options', nullable=False)
    op.alter_column('publish_jobs', 'external_note_id', nullable=False)
    op.alter_column('publish_jobs', 'publish_error', nullable=False)
    op.alter_column('publish_jobs', 'platform_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_publish_jobs_platform'), 'publish_jobs', ['platform'], unique=False)
    op.create_foreign_key(None, 'publish_jobs', 'ai_drafts', ['source_draft_id'], ['id'])
    op.drop_column('publish_jobs', 'updated_at')
    op.drop_column('publish_jobs', 'platform_note_url')
    op.drop_column('publish_jobs', 'content')
    op.drop_column('publish_jobs', 'error_message')
    op.drop_column('publish_jobs', 'platform_note_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_jobs', sa.Column('platform_note_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('publish_jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('publish_jobs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('publish_jobs', sa.Column('platform_note_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('publish_jobs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'publish_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_publish_jobs_platform'), table_name='publish_jobs')
    op.alter_column('publish_jobs', 'platform_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('publish_jobs', 'publish_error')
    op.drop_column('publish_jobs', 'external_note_id')
    op.drop_column('publish_jobs', 'publish_options')
    op.drop_column('publish_jobs', 'publish_mode')
    op.drop_column('publish_jobs', 'body')
    op.drop_column('publish_jobs', 'platform')
    op.drop_column('publish_jobs', 'source_draft_id')
    op.add_column('publish_assets', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('publish_assets', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('publish_assets', sa.Column('local_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('publish_assets', 'creator_upload_info')
    op.drop_column('publish_assets', 'upload_error')
    op.drop_column('publish_assets', 'creator_media_id')
    op.drop_column('publish_assets', 'upload_status')
    op.drop_column('publish_assets', 'file_path')
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_tags_post_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('post_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name=op.f('post_tags_pkey'))
    )
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_note_comments_note_id'), table_name='note_comments')
    op.drop_index(op.f('ix_note_comments_comment_id'), table_name='note_comments')
    op.drop_table('note_comments')
    op.drop_index(op.f('ix_note_assets_note_id'), table_name='note_assets')
    op.drop_table('note_assets')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_platform_account_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_platform'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_platform'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
