"""add_xhs_integration_models

Revision ID: 6c7a5a7ece40
Revises: l9m0n1o2p3q4
Create Date: 2026-05-19 16:07:44.300156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c7a5a7ece40'
down_revision: Union[str, None] = 'l9m0n1o2p3q4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auto_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_tasks_user_id'), 'auto_tasks', ['user_id'], unique=False)
    op.create_table('keyword_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_groups_user_id'), 'keyword_groups', ['user_id'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('login_method', sa.String(length=32), nullable=False),
    sa.Column('phone_mask', sa.String(length=32), nullable=True),
    sa.Column('qr_id', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('qr_url', sa.Text(), nullable=True),
    sa.Column('encrypted_temp_cookies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_sessions_platform'), 'login_sessions', ['platform'], unique=False)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_user_id'), 'model_configs', ['user_id'], unique=False)
    op.create_table('monitoring_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_snapshots_target_id'), 'monitoring_snapshots', ['target_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=32), nullable=True),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_id'), 'platform_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_platform_accounts_platform'), 'platform_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_accounts_user_id'), 'platform_accounts', ['user_id'], unique=False)
    op.create_table('post_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_assets_post_id'), 'post_assets', ['post_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('account_cookie_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_cookies', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_cookie_versions_platform_account_id'), 'account_cookie_versions', ['platform_account_id'], unique=False)
    op.create_table('ai_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_config_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_drafts_user_id'), 'ai_drafts', ['user_id'], unique=False)
    op.create_table('ai_generated_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_config_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_assets_user_id'), 'ai_generated_assets', ['user_id'], unique=False)
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform_account_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_platform_account_id'), 'api_logs', ['platform_account_id'], unique=False)
    op.create_index(op.f('ix_api_logs_user_id'), 'api_logs', ['user_id'], unique=False)
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('publish_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('platform_note_id', sa.String(length=128), nullable=True),
    sa.Column('platform_note_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_jobs_platform_account_id'), 'publish_jobs', ['platform_account_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_user_id'), 'publish_jobs', ['user_id'], unique=False)
    op.create_table('draft_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_draft_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_draft_id'], ['ai_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_assets_ai_draft_id'), 'draft_assets', ['ai_draft_id'], unique=False)
    op.create_table('publish_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_job_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publish_job_id'], ['publish_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_assets_publish_job_id'), 'publish_assets', ['publish_job_id'], unique=False)
    op.drop_index(op.f('ix_comments_platform_comment_id_unique'), table_name='comments')
    op.create_unique_constraint('uq_comments_platform_comment_id', 'comments', ['platform', 'comment_id'])
    op.alter_column('crawl_tasks', 'source_value',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_index(op.f('ix_crm_customers_demand_type'), 'crm_customers', ['demand_type'], unique=False)
    op.create_index(op.f('ix_crm_customers_id'), 'crm_customers', ['id'], unique=False)
    op.create_index(op.f('ix_crm_customers_owner_name'), 'crm_customers', ['owner_name'], unique=False)
    op.create_index(op.f('ix_crm_customers_phone'), 'crm_customers', ['phone'], unique=False)
    op.create_index(op.f('ix_crm_customers_source_post_id'), 'crm_customers', ['source_post_id'], unique=False)
    op.create_index(op.f('ix_crm_customers_status'), 'crm_customers', ['status'], unique=False)
    op.create_index(op.f('ix_crm_follow_records_next_follow_up_at'), 'crm_follow_records', ['next_follow_up_at'], unique=False)
    op.drop_index(op.f('ix_posts_platform_post_id_unique'), table_name='posts')
    op.create_unique_constraint('uq_posts_platform_post_id', 'posts', ['platform', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_posts_platform_post_id', 'posts', type_='unique')
    op.create_index(op.f('ix_posts_platform_post_id_unique'), 'posts', ['platform', 'post_id'], unique=True)
    op.drop_index(op.f('ix_crm_follow_records_next_follow_up_at'), table_name='crm_follow_records')
    op.drop_index(op.f('ix_crm_customers_status'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_source_post_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_phone'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_owner_name'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_demand_type'), table_name='crm_customers')
    op.alter_column('crawl_tasks', 'source_value',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_constraint('uq_comments_platform_comment_id', 'comments', type_='unique')
    op.create_index(op.f('ix_comments_platform_comment_id_unique'), 'comments', ['platform', 'comment_id'], unique=True)
    op.drop_index(op.f('ix_publish_assets_publish_job_id'), table_name='publish_assets')
    op.drop_table('publish_assets')
    op.drop_index(op.f('ix_draft_assets_ai_draft_id'), table_name='draft_assets')
    op.drop_table('draft_assets')
    op.drop_index(op.f('ix_publish_jobs_user_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_platform_account_id'), table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_api_logs_user_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_platform_account_id'), table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index(op.f('ix_ai_generated_assets_user_id'), table_name='ai_generated_assets')
    op.drop_table('ai_generated_assets')
    op.drop_index(op.f('ix_ai_drafts_user_id'), table_name='ai_drafts')
    op.drop_table('ai_drafts')
    op.drop_index(op.f('ix_account_cookie_versions_platform_account_id'), table_name='account_cookie_versions')
    op.drop_table('account_cookie_versions')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_post_assets_post_id'), table_name='post_assets')
    op.drop_table('post_assets')
    op.drop_index(op.f('ix_platform_accounts_user_id'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_platform'), table_name='platform_accounts')
    op.drop_index(op.f('ix_platform_accounts_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_monitoring_snapshots_target_id'), table_name='monitoring_snapshots')
    op.drop_table('monitoring_snapshots')
    op.drop_index(op.f('ix_model_configs_user_id'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_platform'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_keyword_groups_user_id'), table_name='keyword_groups')
    op.drop_table('keyword_groups')
    op.drop_index(op.f('ix_auto_tasks_user_id'), table_name='auto_tasks')
    op.drop_table('auto_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
